### ISSUE TITLE
Bug in DEFAULT_MAPPER

### ISSUE THREAD

**Issue by eliseumds** [evenchange4/react-intl-po#19]
https://github.com/evenchange4/react-intl-po/blob/master/src/readAllPOAsObjectSync.js#L6-L8

Is this function supposed to extract the filename? If so, I would expect a regular expression that gets everything after a slash (if it exists) and before ".po":

```js
return filename.match(/^(.*\/)*(.*)\.po$/)[2];
```

I stumbled upon after trying out the following command and getting an exception:

```sh
$ rip po2json './*.po' -m './build/messages/src/**/*.json' -o result.json
./node_modules/react-intl-po/lib/readAllPOAsObjectSync.js:27
  return filename.match(/[^.]\.(.*)\.po$/)[1];
                                          ^

TypeError: Cannot read property '1' of null
```

**Comment by eliseumds** [comment]
Ah, I just realised that the RegExp is made to work with "somestring.*.po". Anyway, why is this prefix required?

**Comment by evenchange4** [comment]
Thanks for bug report! 😄

The `localeMapper` function is expect to return `locale` string.

For example:

```js
localeMapper('./po/project.en.po')    //=> return 'en'
localeMapper('./po/project.zh-cn.po') //=> return 'zh-cn'
```

**Comment by MorrisGallego** [comment]
And why not make the RegExp return the field just before the file extension? That way you don't force your users to have a prefix... 

Something like this could work:
```javascript
return filename.match(/([^.]*\.)*([^.]+)\.po$/)[2]
```

**Comment by evenchange4** [comment]
Thanks! It works. 👍
