### ISSUE TITLE
One file for each language

### ISSUE THREAD

**Issue by MorrisGallego** [evenchange4/react-intl-po#29]
Hi,

First of all thank you very mucho for this tool, it's very useful. 
I was wondering if it could be posible to add an option to generate **a .json for each .po** in place of a single .json with all the localizations inside (in my case it's better to have the translations in different files).

Let me know if I can help, please. 
And thanks again!

**Comment by evenchange4** [comment]
Awesome!! 
I think it's very helpful serving separate translation .json file for SPA site.
Thanks for the great work. 💪

**Comment by evenchange4** [comment]
Thanks! Released `v1.0.7` with your changes.
And I use pathname to control it instead of `--multi` flag, please try [Case 1](https://github.com/evenchange4/react-intl-po#po2json).
