### ISSUE TITLE
React-intl 1 and/or 2?

### ISSUE THREAD

**Issue by JohnPhoto** [evenchange4/react-intl-po#53]
Hello
Is this library supposed to be used with react-intl v1 or v2?

**Comment by evenchange4** [comment]
The library currently only supports react-intl `^2.0.0`, I will update the README file.

Sorry for the inconvenience! 😿

**Comment by JohnPhoto** [comment]
Thank you for the info, I am using v2 so thats perfectly fine. But it would be nice to have it in readme. And also maybe as a peerDependency in package.json?

**Comment by evenchange4** [comment]
Closed via https://github.com/evenchange4/react-intl-po/commit/ec5f7b90b848b1f8d6f49de25e08a8cbb1c50d74 . Thanks! 🙌
