### ISSUE TITLE
Suggestion: work with `id` for `msgid` leads to missing `defaultMessage` data

### ISSUE THREAD

**Issue by Guibod** [evenchange4/react-intl-po#57]
The actual behavior of react-intl-po allow usage of `defaultMessage` as `msgid` by default. Which is in most situation enough. In my case, I opted for `id` as  `msgid`, that's to allow different translation in different locations. That's well enough documented in the last section of the README.md file.

Gettext `msgid` is not always enough to produce a proper translation for each language, as gettext don't support the `defaultMessage` mechanism of `react-intl`. The result is that we lose this value as we generate the original POT file.
Gettext/POT really don't support the concept of default message which is really SUPER painful. So I digged [POT file format documentation](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html) and came to with some solutions:

### Solution 1 - Add another `#.` with the defaultMessage value in it. (my favorite)
```
#: messages/_default.json
#. [Activities.filter.irrelevant.none] - Message description
#. Afficher les mentions pertinentes
msgid "Activities.filter.irrelevant.none"
msgstr ""
```
![reactintlpo-dotcomment](https://cloud.githubusercontent.com/assets/840033/22403383/af5d062c-e615-11e6-8f59-68aab0518844.png)

This solution is pretty satisfactory, yet i found really hard for my translator to copy/paste the value. Say you have a french application (my case) with text wrote by developer (me) so that the defaultMessage are in 'French pirate', if my product owner want to generate a true french version with nice words he may want to reuse most of my original text.
Yet, POEDIT don't allow easy copy/paste between comments for translators and the translation field. That's annoying. That's the only caveat i found yet.

### Solution 2 - Add a `#|` with the defaultMessage value in it
```
#: messages/_default.json
#. [Activities.filter.irrelevant.all] - Message description
#| Afficher toutes les mentions
msgid "Activities.filter.irrelevant.all"
msgstr ""
```
![reactintlpo-pipecomment](https://cloud.githubusercontent.com/assets/840033/22403385/b3a716be-e615-11e6-805c-33f3580e82a6.png)

To my understanding, pipe comments are used by poedit to support crash recovery or temporary data while merging. I am really not sure that it is a good idea to use that.
In PO documentation though, it is stated that we can use the `#| msgctxt previous-context` syntax but it is rawly displayed in POEDIT.

### Solution 3 - defaultMessage in `msgstr` (Not working)
```
#: messages/_default.json
#. [Activities.filter.irrelevant.only] - Message description
msgid "Activities.filter.irrelevant.only"
msgstr "Afficher les mentions non-pertinentes"
```

![reactintlpo-msgstr](https://cloud.githubusercontent.com/assets/840033/22403381/aa31a068-e615-11e6-8b0c-dd14d3a49067.png)

Another solution I tried is to put defaultMessage in `msgstr` in the generated pot file. But it has good effect on the file **as `msgmerge` fails** in the way you see on the following screenshot:

![reactintlpo-msgstr-error](https://cloud.githubusercontent.com/assets/840033/22403379/a53111f2-e615-11e6-8cef-51106d7970c8.png)

Do you think we can add this feature as stated in solution 1 as a feature to react-intl-po ?
If so, should this `defaultMessage` comment should be always added or only in case of `-k id` mapping ?

**Comment by Guibod** [comment]
I created a PR implementing solution 1
https://github.com/evenchange4/react-intl-po/pull/60

**Comment by evenchange4** [comment]
Good catch! This is very helpful for translators if developers can always provide enough information.

> Do you think we can add this feature as stated in solution 1 as a feature to react-intl-po ?

To avoid break the origin pipe behavior of Poedit, it is true that solution 1 would be better than solution 2.

By the way, should the sample code of first two solution be exchanged?

> If so, should this defaultMessage comment should be always added or only in case of -k id mapping ?

To simplify code base, I think it is okay that we add the comment for all the case.

And for the UX of translators, the information should always be put to the same place on the right panel of Poedit even in different case.

**Comment by Guibod** [comment]
I've edited the code sample.

**Comment by evenchange4** [comment]
Finally releasing `v2.0.1` with solution 1. 🙌
