### ISSUE TITLE
Working with default mapping (defautMessage => msgid) don't allow `msgid` duplicates in a same file

### ISSUE THREAD

**Issue by Guibod** [evenchange4/react-intl-po#59]
In my case, all my translations from `babel-react-intl-plugin` are merged into a default json file. When I want to use the default json2pot behavior, it won't merge messages sharing the same `msgid` / `defaultMessage`.

From my understanding it came from the fact that every file builds a map of `msgid` / message data. Before the real mapping to occur. I guess it would be better to generate an array of message data for each file, then merge them all through map/reduce, later allowing duplicated msgid in the same file.

To reproduce this, simply put two string sharing the same defaultMessage in a same file.

**Comment by xobb1t** [comment]
@Guibod got same result.

**Comment by evenchange4** [comment]
It now allows duplicated `key` in the same file.

Please try `v2.0.0` (with some [breaking changes of internal functions](https://github.com/evenchange4/react-intl-po/blob/master/CHANGELOG.md#v200).)  and feel free to reopen this issue if there is any problems. 

Thanks! 😄
