### ISSUE TITLE
Rip command not found with zsh

### ISSUE THREAD

**Issue by saadaouad** [evenchange4/react-intl-po#74]
Any idea about this please `zsh: command not found: rip` ? 
I have some error with bash !

**Comment by evenchange4** [comment]
Did you want to use CLI globally? You should install it via `$ npm i react-intl-po -g`.

**Comment by evenchange4** [comment]
Close it. Please feel free to reopen this issue if the problem still not been solved.

**Comment by saadaouad** [comment]
Working now, Thanks @evenchange4
