### ISSUE TITLE
TypeError: messages.reduce is not a function

### ISSUE THREAD

**Issue by CrmDev23** [evenchange4/react-intl-po#80]
When I try to run "react-intl-po po2json ./output/de.po -m ./output/**/*.json -o ./output/de.json", I'll get the error message "TypeError: messages.reduce is not a function".
Input de.po file:
```
msgid ""
msgstr ""
"POT-Creation-Date: 2017-06-23 13:32+0200\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"MIME-Version: 1.0\n"
"X-Generator: Poedit 2.0.2\n"
"Project-Id-Version: \n"
"PO-Revision-Date: \n"
"Language-Team: \n"
"Last-Translator: \n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"Language: de\n"

#. [welcome]
#. defaultMessage is:
#. Hello Michael Hsu!
#: output/messages.json
msgid "Hello Michael Hsu!"
msgstr "Hallo Michael Hsu DE!"
```

**Comment by evenchange4** [comment]
Hi @CrmDev23, could you try to use the commands like this: 

```diff
-"react-intl-po po2json ./output/de.po -m ./output/**/*.json -o ./output/de.json"
+"react-intl-po po2json './output/de.po' -m './output/**/*.json' -o './output/de.json'"
```

**Comment by CrmDev23** [comment]
Thanks for your quick answer: Unfortunately still the same.
```
TypeError: messages.reduce is not a function
    at C:\Users\ciaomatteo\Documents\GitHub\xrmcalculator\node_modules\react-intl-po\lib\readAllMessageAsObjectSync.js:38:21
```
The other commands are working fine (extract:messages, extract:pot).

**Comment by evenchange4** [comment]
I have no idea what's going wrong on this use case. 😔
It would be great if you could provide a simple repo so that I can reproduce it.
Thanks!

**Comment by CrmDev23** [comment]
Ok, I found the issue:
It only occurs if the output json file already exists. So I can easily workaround it, by deleting the file in advance.
Thanks!

**Comment by evenchange4** [comment]
Close it for now. 
Please feel free to reopen the issue, and it is always welcome to send a PR even if a document improvement to avoid this case. 😀
