### ISSUE TITLE
How to update existing translations ?

### ISSUE THREAD

**Issue by tonydtran** [evenchange4/react-intl-po#94]
Hi,

Thank you for your huge work, it makes my life so easier!

I just have one question:
React-intl-po works really great when you need to generate translation once your project is finished. But what about the case when you need to update your project by adding new contents? Maybe I am wrong but when you generate once again the json and the .pot file you need to start over the translation.

Maybe I miss something or use badly your tool?

Thanks.

**Comment by tonydtran** [comment]
Hi,

I've found the solution. .pot file is already updated with former translations.

Sorry for disturbing you!

**Comment by evenchange4** [comment]
Cool, no worry! 😄
